# Which ocamlfind/camlp4/ ... version to use?
# ocamlfind will choose automatically the compiler.
OCAMLFIND=ocamlfind
CAMLP4=camlp4
CAMLLEX=ocamllex
CAMLYACC=ocamlyacc
CAMLCNAME=ocamlc
CAMLOPTNAME=ocamlopt
CAMLMKTOPNAME=ocamlmktop
CAMLMKLIB=ocamlmklib
CAMLCPNAME=ocamlcp -p a # No: profiling is incompatible with the -pp option
CHOWN=chown
CC=gcc

CAMLINCLUDE=-I /home/pad/packages/Linux/stow/ocaml-3.12/lib/ocaml

## The root directory for the package install (usually /)
#ROOT = 

# Temporary root directory to install the package (usually always "" but for package makers)
TEMPROOT = 

# Do you want the bytecode version ? YES/NO
BYTECODE=YES

# Do you want the native code version (ocsigen.opt) ? YES/NO
NATIVECODE=YES

# Do you want to use dynamic linking for native code? YES/NO
NATDYNLINK=YES

# Do you want the ocamlduce extension? (YES/NO)
# (You need ocamlduce to be installed)
OCAMLDUCE=NO
# If you have OCamlduce installed, which ocamlducefind do you want?
OCAMLDUCEFIND=ocamlducefind

# The directory for ocsigen server (binary):
BINDIR = /usr/local/bin

# The directory for ocsigen manpage:
MANDIR = /usr/local/share/man/man1

# Where to install the directory for ocsigen extensions:
MODULEINSTALLDIR = $(shell $(OCAMLFIND) printconf destdir)

# Where to install stub libraries
STUBDIR = $(shell head -n1 $(shell $(OCAMLFIND) printconf ldconf))

# Where to install the directory for ocsigen extensions' libraries (e.g. ocsidbm):
EXTRALIBDIR = /usr/local/lib/$(OCSIGENNAME)

# Where to install eliomtests:
ELIOMTESTSINSTALLDIR = /usr/local/lib/$(OCSIGENNAME)/eliomtests

# User who will run Ocsigen server (not root) (eg, for debian, www-data)
# (This user must exist on your system)
OCSIGENUSER=www-data

# group who will run Ocsigen server (not root) (eg, for debian, www-data)
# (This group must exist)
OCSIGENGROUP=www-data

# The name of the server (and the directory for the extensions)
OCSIGENNAME=ocsigen

# ocsigen's logs:
LOGDIR = /var/log/$(OCSIGENNAME)

# Config files:
CONFIGDIR = /etc/$(OCSIGENNAME)

# Where to put static pages:
STATICPAGESDIR =/var/www/$(OCSIGENNAME)

# Where to put dynamic data:
DATADIR = /var/lib/$(OCSIGENNAME)

# Default directory for file upload:
UPLOADDIR = /tmp

# Where to put Ocsigen documentation:
DOCDIR = /usr/local/share/doc/$(OCSIGENNAME)

# Do you want debugging information? (-g)
DEBUG=NO

# Do you want annot files? (-dtypes)
ANNOT=NO

# The name of the named pipe used to command the server
COMMANDPIPE=/var/run/ocsigen_command

# Do you want deflatemod? (requires camlzip)
CAMLZIP=NO

# The name of camlzip package:
CAMLZIPNAME=

# Do you want ocsipersist with sqlite?
OCSIPERSISTSQLITE=NO

# Do you want ocsipersist with dbm?
OCSIPERSISTDBM=YES

# The source directory
SRC=/home/pad/ocsigen

# If you are using ocamlnet 1, leave empty.
NETSYS=netsys,

#
RLWRAP=

# Profiling (always put NO here - but if you want to debug ocsigen):
PROFILING=NO

# Do not modify this
LIBDIRS= -I ../commons -I ../http -I ../web_html -I ../server -I ../extensions -I ../eliom -I ../eliom/extensions
LIBDIRS2= -I ../../commons -I ../../http -I ../../web_html -I ../../server -I ../../extensions -I ../../eliom -I ../../eliom/extensions
LIBDIRS3= -I commons -I http -I web_html -I server -I extensions -I eliom -I eliom/extensions

include $(SRC)/Makefile.options

