
# The name of the library, ocamlfind package, etc.
PROJECTNAME := eliom

#### External binaries ####

OCAMLFIND   := ocamlfind
OCAMLMKLIB  := ocamlmklib
JS_OF_OCAML := js_of_ocaml
CC          := gcc
INSTALL     := install

# optionnal
OCAMLDUCEFIND := ocamlducefind



### Options ###

# Do you want the ocamlduce extension? YES/NO
# (You need ocamlduce to be installed)
OCAMLDUCE:=NO

# Do you want preemptive threads ? YES/NO
PREEMPTIVE:=YES

# Do you want to use dynamic linking for native code? YES/NO
NATDYNLINK:=YES

# Do you want debugging information (-g) ? YES/NO
DEBUG:=NO

# Do you want annot files (-dtypes) ? YES/NO
ANNOT:=NO

# Profiling (always put NO here - but if you want to debug eliom):
PROFILING:=NO



### Paths ###

# Temporary root directory to install the package (usually always "" but for package makers)
TEMPROOT = 

# The directory for eliom compiler (binary):
BINDIR := /usr/local/bin

# Where to install Eliom libraries:
LIBDIR := $(shell ${OCAMLFIND} printconf destdir)

# Where to put Eliom documentation:
DOCDIR := /usr/local/share/doc/$(PROJECTNAME)

# The source directory (needed for local testing)
SRC := /home/pad/ocsigen/eliom

include $(SRC)/Makefile.options

