
# The name of the server, the ocamlfind package, etc.
PROJECTNAME := ocsigenserver

#### External binaries ####

OCAMLFIND := ocamlfind
OCAMLLEX  := ocamllex
OCAMLMKLIB:= ocamlmklib
CHOWN     := chown
CHMOD     := chmod
INSTALL   := install
CC        := gcc

# optionnal
RLWRAP    := rlwrap


### Options ###

# User who will run Ocsigen server (not root) (eg, for debian, www-data)
# (This user must exist on your system)
OCSIGENUSER := www-data

# group who will run Ocsigen server (not root) (eg, for debian, www-data)
# (This group must exist)
OCSIGENGROUP := www-data

# Do you want deflatemod? YES/NO (requires camlzip)
CAMLZIP:=NO

# The name of camlzip package:
CAMLZIPNAME:=

# Do you want ocsipersist with sqlite? YES/NO
OCSIPERSISTSQLITE:=NO

# Do you want ocsipersist with dbm? YES/NO
OCSIPERSISTDBM:=YES

# Do you want preemptive threads ? YES/NO
PREEMPTIVE:=YES

# Do you want debugging information (-g) ? YES/NO
DEBUG:=NO

# Do you want annot files (-dtypes) ? YES/NO
ANNOT:=NO

# Profiling (always put NO here - but if you want to debug ocsigen):
PROFILING:=NO



### Paths ###

# Temporary root directory to install the package (usually always "" but for package makers)
TEMPROOT := 

# Do you want to use dynamic linking for native code? YES/NO
NATDYNLINK:=YES

# The directory for ocsigen server (binary):
BINDIR := /usr/local/bin

# The directory for ocsigen manpage:
MANDIR := /usr/local/share/man/man1

# Where to install the libraries
LIBDIR := $(shell ${OCAMLFIND} printconf destdir)

# ocsigen's logs:
LOGDIR := /var/log/$(PROJECTNAME)

# Config files:
CONFIGDIR := /etc/$(PROJECTNAME)

# Where to put static pages:
STATICPAGESDIR := /var/www/$(PROJECTNAME)

# Where to put dynamic data:
DATADIR := /var/lib/$(PROJECTNAME)

# Default directory for file upload:
UPLOADDIR := /tmp

# Where to put Ocsigen documentation:
DOCDIR := /usr/local/share/doc/$(PROJECTNAME)

# The name of the named pipe used to command the server
COMMANDPIPE := /var/run/$(PROJECTNAME)_command

# The source directory
SRC := /home/pad/ocsigen/server

include $(SRC)/Makefile.options
